// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { BulkUpsertProductsProductsUpdateManyPostData, BulkUpsertProductsProductsUpdateManyPostErrors, BulkUpsertProductsProductsUpdateManyPostResponses, GetPhpSessionIdPhpSessIdPostData, GetPhpSessionIdPhpSessIdPostErrors, GetPhpSessionIdPhpSessIdPostResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, InitDbInitDbPostData, InitDbInitDbPostResponses, UpsertWarehouseItemsWarehouseItemsUpdateManyPostData, UpsertWarehouseItemsWarehouseItemsUpdateManyPostErrors, UpsertWarehouseItemsWarehouseItemsUpdateManyPostResponses, UpsertWarehouseWarehousesUpdatePostData, UpsertWarehouseWarehousesUpdatePostErrors, UpsertWarehouseWarehousesUpdatePostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Init Db
 */
export const initDbInitDbPost = <ThrowOnError extends boolean = false>(options?: Options<InitDbInitDbPostData, ThrowOnError>) => (options?.client ?? client).post<InitDbInitDbPostResponses, unknown, ThrowOnError>({ url: '/init_db', ...options });

/**
 * Bulk Upsert Products
 */
export const bulkUpsertProductsProductsUpdateManyPost = <ThrowOnError extends boolean = false>(options: Options<BulkUpsertProductsProductsUpdateManyPostData, ThrowOnError>) => (options.client ?? client).post<BulkUpsertProductsProductsUpdateManyPostResponses, BulkUpsertProductsProductsUpdateManyPostErrors, ThrowOnError>({
    url: '/products/update_many',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upsert Warehouse
 */
export const upsertWarehouseWarehousesUpdatePost = <ThrowOnError extends boolean = false>(options: Options<UpsertWarehouseWarehousesUpdatePostData, ThrowOnError>) => (options.client ?? client).post<UpsertWarehouseWarehousesUpdatePostResponses, UpsertWarehouseWarehousesUpdatePostErrors, ThrowOnError>({
    url: '/warehouses/update',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upsert Warehouse Items
 */
export const upsertWarehouseItemsWarehouseItemsUpdateManyPost = <ThrowOnError extends boolean = false>(options: Options<UpsertWarehouseItemsWarehouseItemsUpdateManyPostData, ThrowOnError>) => (options.client ?? client).post<UpsertWarehouseItemsWarehouseItemsUpdateManyPostResponses, UpsertWarehouseItemsWarehouseItemsUpdateManyPostErrors, ThrowOnError>({
    url: '/warehouse_items/update_many',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Php Session Id
 *
 * Retrieve PHP session ID by logging into Upfit.
 *
 * - username: Upfit account username
 * - password: Upfit account password
 */
export const getPhpSessionIdPhpSessIdPost = <ThrowOnError extends boolean = false>(options: Options<GetPhpSessionIdPhpSessIdPostData, ThrowOnError>) => (options.client ?? client).post<GetPhpSessionIdPhpSessIdPostResponses, GetPhpSessionIdPhpSessIdPostErrors, ThrowOnError>({
    url: '/php_sess_id/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health Check
 *
 * Health check endpoint
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
