// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://expobarcodereadertest-production.up.railway.app' | (string & {});
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Error Code
     */
    error_code: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Product
 */
export type Product = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Price
     */
    price: number | null;
};

/**
 * SessionResponse
 */
export type SessionResponse = {
    /**
     * Phpsessid
     */
    PHPSESSID: string;
    /**
     * Clubname
     */
    clubName: string;
    /**
     * Clubid
     */
    clubId: string;
};

/**
 * UpfitAccount
 */
export type UpfitAccount = {
    /**
     * Username
     *
     * Username for Upfit account
     */
    username: string;
    /**
     * Password
     *
     * Password for Upfit account
     */
    password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * Warehouse
 */
export type Warehouse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * WarehouseItem
 */
export type WarehouseItem = {
    /**
     * Warehouse Id
     */
    warehouse_id: string;
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Quantity
     */
    quantity: string;
};

export type InitDbInitDbPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/init_db';
};

export type InitDbInitDbPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BulkUpsertProductsProductsUpdateManyPostData = {
    /**
     * Products
     */
    body: Array<Product>;
    path?: never;
    query?: never;
    url: '/products/update_many';
};

export type BulkUpsertProductsProductsUpdateManyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkUpsertProductsProductsUpdateManyPostError = BulkUpsertProductsProductsUpdateManyPostErrors[keyof BulkUpsertProductsProductsUpdateManyPostErrors];

export type BulkUpsertProductsProductsUpdateManyPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpsertWarehouseWarehousesUpdatePostData = {
    body: Warehouse;
    path?: never;
    query?: never;
    url: '/warehouses/update';
};

export type UpsertWarehouseWarehousesUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertWarehouseWarehousesUpdatePostError = UpsertWarehouseWarehousesUpdatePostErrors[keyof UpsertWarehouseWarehousesUpdatePostErrors];

export type UpsertWarehouseWarehousesUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpsertWarehouseItemsWarehouseItemsUpdateManyPostData = {
    /**
     * Warehouse Items
     */
    body: Array<WarehouseItem>;
    path?: never;
    query?: never;
    url: '/warehouse_items/update_many';
};

export type UpsertWarehouseItemsWarehouseItemsUpdateManyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertWarehouseItemsWarehouseItemsUpdateManyPostError = UpsertWarehouseItemsWarehouseItemsUpdateManyPostErrors[keyof UpsertWarehouseItemsWarehouseItemsUpdateManyPostErrors];

export type UpsertWarehouseItemsWarehouseItemsUpdateManyPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPhpSessionIdPhpSessIdPostData = {
    body: UpfitAccount;
    path?: never;
    query?: never;
    url: '/php_sess_id/';
};

export type GetPhpSessionIdPhpSessIdPostErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorResponse;
    /**
     * Failed to connect to Upfit service
     */
    502: ErrorResponse;
    /**
     * Request timed out
     */
    504: ErrorResponse;
};

export type GetPhpSessionIdPhpSessIdPostError = GetPhpSessionIdPhpSessIdPostErrors[keyof GetPhpSessionIdPhpSessIdPostErrors];

export type GetPhpSessionIdPhpSessIdPostResponses = {
    /**
     * Successfully retrieved session ID
     */
    200: SessionResponse;
};

export type GetPhpSessionIdPhpSessIdPostResponse = GetPhpSessionIdPhpSessIdPostResponses[keyof GetPhpSessionIdPhpSessIdPostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
